environment:
  ENV: production
packages:
  - name: database-backup
    environment:
      S3_ENDPOINT: https://nyc3.digitaloceanspaces.com
      S3_ACCESS_KEY: DO00NJAX9XDKE98ENG6E
      S3_SECRET_KEY: 8CvRkYNv2qoyng12d2VFzwo/hGJSJ4i8AzJ5/0Fay14
      S3_BUCKET: jack-general
      S3_REGION: us-east-1
      MYSQL_HOST: db.jackcrane.rocks
      MYSQL_USER: apps
      MYSQL_PASSWORD: Guro6297
      DATABASES: '["skisavvy", "shadyurl"]'
      BACKUP_RETENTION: "96"
      PREFIX: db_backups
      MONITORING_WEBHOOK: https://betteruptime.com/api/v1/heartbeat/igspVdcLjAqokoyhsf3JsHPe
    functions:
      - name: mysql-s3-backup
        runtime: "nodejs:18"
        limits:
          timeout: 300000
        environment:
          S3_ENDPOINT: https://nyc3.digitaloceanspaces.com
          S3_ACCESS_KEY: DO00NJAX9XDKE98ENG6E
          S3_SECRET_KEY: 8CvRkYNv2qoyng12d2VFzwo/hGJSJ4i8AzJ5/0Fay14
          S3_BUCKET: jack-general
          S3_REGION: us-east-1
          MYSQL_HOST: db.jackcrane.rocks
          MYSQL_USER: apps
          MYSQL_PASSWORD: Guro6297
          DATABASES: '["skisavvy", "shadyurl"]'
          BACKUP_RETENTION: "96"
          PREFIX: db_backups
          MONITORING_WEBHOOK: https://betteruptime.com/api/v1/heartbeat/igspVdcLjAqokoyhsf3JsHPe
